[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CuTropicalGEMM = "c2b282c3-c9c2-431d-80f7-a1a0561ebe55"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EliminateGraphs = "b3ff564c-d3b6-11e9-0ef2-9b4ae9f9cbe1"
GenericTensorNetworks = "3521c873-ad32-4bb4-b63d-f4f178f42b49"
GraphIO = "aa1b3936-2fda-51b9-ab35-c553d3a640a2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
OMEinsumContractionOrders = "6f22d1fd-8eed-4bb7-9776-e7d684900715"
OptimalBranching = "96e750e4-2b4b-404e-96bc-6769eb2ae924"
OptimalBranchingCore = "c76e7b22-e1d2-40e8-b0f1-f659837787b8"
OptimalBranchingMIS = "1d45bab8-fbcd-445a-8de2-8d643ff389c2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
ProblemReductions = "899c297d-f7d2-4ebf-8815-a35996def416"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
TensorBranching = "86172e9d-0750-4338-909c-b7a43d7b620d"
TropicalNumbers = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"
UnitDiskMapping = "1b61a8d9-79ed-4491-8266-ef37f39e1727"
