name = "OptimalBranching"
uuid = "96e750e4-2b4b-404e-96bc-6769eb2ae924"
authors = ["Xuanzhao Gao <xz.gao@connect.ust.hk> and Jin-Guo Liu and Yijia Wang and Zhongyi Ni"]
version = "0.2.0"

[deps]
GenericTensorNetworks = "3521c873-ad32-4bb4-b63d-f4f178f42b49"
OptimalBranchingCore = "c76e7b22-e1d2-40e8-b0f1-f659837787b8"
OptimalBranchingMIS = "1d45bab8-fbcd-445a-8de2-8d643ff389c2"
ProblemReductions = "899c297d-f7d2-4ebf-8815-a35996def416"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"


[compat]
GenericTensorNetworks = "3, 4"
OptimalBranchingCore = "0.1"
OptimalBranchingMIS = "0.2"
ProblemReductions = "0.3.4"
Reexport = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
